# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/snifferMainWindow.ui'
#
# Created: Sat Sep 26 11:29:29 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SnifferMainWindow(object):
    def setupUi(self, SnifferMainWindow):
        SnifferMainWindow.setObjectName("SnifferMainWindow")
        SnifferMainWindow.resize(880, 611)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/logoZigBee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SnifferMainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(SnifferMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treePackets = QtGui.QTreeView(self.groupBox)
        self.treePackets.setIndentation(10)
        self.treePackets.setRootIsDecorated(False)
        self.treePackets.setItemsExpandable(False)
        self.treePackets.setWordWrap(True)
        self.treePackets.setObjectName("treePackets")
        self.verticalLayout.addWidget(self.treePackets)
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeDetails = QtGui.QTreeWidget(self.groupBox_2)
        self.treeDetails.setWordWrap(True)
        self.treeDetails.setObjectName("treeDetails")
        self.treeDetails.headerItem().setText(0, "Field")
        self.treeDetails.header().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.treeDetails)
        self.horizontalLayout_4.addWidget(self.splitter)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupFile = QtGui.QGroupBox(self.centralwidget)
        self.groupFile.setMinimumSize(QtCore.QSize(201, 0))
        self.groupFile.setMaximumSize(QtCore.QSize(201, 16777215))
        self.groupFile.setObjectName("groupFile")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupFile)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnNew = QtGui.QToolButton(self.groupFile)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNew.setIcon(icon1)
        self.btnNew.setIconSize(QtCore.QSize(32, 32))
        self.btnNew.setObjectName("btnNew")
        self.horizontalLayout.addWidget(self.btnNew)
        self.btnImport = QtGui.QToolButton(self.groupFile)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnImport.setIcon(icon2)
        self.btnImport.setIconSize(QtCore.QSize(32, 32))
        self.btnImport.setObjectName("btnImport")
        self.horizontalLayout.addWidget(self.btnImport)
        self.btnSave = QtGui.QToolButton(self.groupFile)
        self.btnSave.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon3)
        self.btnSave.setIconSize(QtCore.QSize(32, 32))
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.verticalLayout_4.addWidget(self.groupFile)
        self.groupSniff = QtGui.QGroupBox(self.centralwidget)
        self.groupSniff.setMinimumSize(QtCore.QSize(201, 0))
        self.groupSniff.setMaximumSize(QtCore.QSize(201, 16777215))
        self.groupSniff.setObjectName("groupSniff")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupSniff)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSniff = QtGui.QToolButton(self.groupSniff)
        self.btnSniff.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSniff.setIcon(icon4)
        self.btnSniff.setIconSize(QtCore.QSize(32, 32))
        self.btnSniff.setObjectName("btnSniff")
        self.horizontalLayout_2.addWidget(self.btnSniff)
        self.btnScanChannel = QtGui.QToolButton(self.groupSniff)
        self.btnScanChannel.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/page-zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnScanChannel.setIcon(icon5)
        self.btnScanChannel.setIconSize(QtCore.QSize(32, 32))
        self.btnScanChannel.setObjectName("btnScanChannel")
        self.horizontalLayout_2.addWidget(self.btnScanChannel)
        self.btnScanChannels = QtGui.QToolButton(self.groupSniff)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/page-zoom2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnScanChannels.setIcon(icon6)
        self.btnScanChannels.setIconSize(QtCore.QSize(32, 32))
        self.btnScanChannels.setObjectName("btnScanChannels")
        self.horizontalLayout_2.addWidget(self.btnScanChannels)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.treeChannels = QtGui.QTreeView(self.groupSniff)
        self.treeChannels.setIndentation(10)
        self.treeChannels.setRootIsDecorated(False)
        self.treeChannels.setItemsExpandable(False)
        self.treeChannels.setObjectName("treeChannels")
        self.treeChannels.header().setDefaultSectionSize(39)
        self.verticalLayout_3.addWidget(self.treeChannels)
        self.verticalLayout_4.addWidget(self.groupSniff)
        self.groupNetwork = QtGui.QGroupBox(self.centralwidget)
        self.groupNetwork.setEnabled(True)
        self.groupNetwork.setMinimumSize(QtCore.QSize(201, 0))
        self.groupNetwork.setMaximumSize(QtCore.QSize(201, 16777215))
        self.groupNetwork.setObjectName("groupNetwork")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupNetwork)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnNameNodes = QtGui.QToolButton(self.groupNetwork)
        self.btnNameNodes.setEnabled(False)
        self.btnNameNodes.setIconSize(QtCore.QSize(32, 32))
        self.btnNameNodes.setObjectName("btnNameNodes")
        self.horizontalLayout_3.addWidget(self.btnNameNodes)
        self.btnStatistics = QtGui.QToolButton(self.groupNetwork)
        self.btnStatistics.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/view-statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStatistics.setIcon(icon7)
        self.btnStatistics.setIconSize(QtCore.QSize(32, 32))
        self.btnStatistics.setObjectName("btnStatistics")
        self.horizontalLayout_3.addWidget(self.btnStatistics)
        self.verticalLayout_4.addWidget(self.groupNetwork)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.setStretch(0, 10)
        SnifferMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SnifferMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSniffer = QtGui.QMenu(self.menubar)
        self.menuSniffer.setObjectName("menuSniffer")
        self.menuNetwork = QtGui.QMenu(self.menubar)
        self.menuNetwork.setEnabled(True)
        self.menuNetwork.setObjectName("menuNetwork")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        SnifferMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SnifferMainWindow)
        self.statusbar.setObjectName("statusbar")
        SnifferMainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(SnifferMainWindow)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName("actionNew")
        self.actionImport = QtGui.QAction(SnifferMainWindow)
        self.actionImport.setIcon(icon2)
        self.actionImport.setObjectName("actionImport")
        self.actionSave = QtGui.QAction(SnifferMainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtGui.QAction(SnifferMainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/window-close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon8)
        self.actionExit.setObjectName("actionExit")
        self.actionScan_channels = QtGui.QAction(SnifferMainWindow)
        self.actionScan_channels.setIcon(icon6)
        self.actionScan_channels.setObjectName("actionScan_channels")
        self.actionScan_channel = QtGui.QAction(SnifferMainWindow)
        self.actionScan_channel.setEnabled(False)
        self.actionScan_channel.setIcon(icon5)
        self.actionScan_channel.setObjectName("actionScan_channel")
        self.actionSniff = QtGui.QAction(SnifferMainWindow)
        self.actionSniff.setEnabled(False)
        self.actionSniff.setIcon(icon4)
        self.actionSniff.setObjectName("actionSniff")
        self.actionPort_settings = QtGui.QAction(SnifferMainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPort_settings.setIcon(icon9)
        self.actionPort_settings.setObjectName("actionPort_settings")
        self.actionStatistics = QtGui.QAction(SnifferMainWindow)
        self.actionStatistics.setEnabled(False)
        self.actionStatistics.setIcon(icon7)
        self.actionStatistics.setObjectName("actionStatistics")
        self.actionNetwork_structure = QtGui.QAction(SnifferMainWindow)
        self.actionNetwork_structure.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/nepomuk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNetwork_structure.setIcon(icon10)
        self.actionNetwork_structure.setObjectName("actionNetwork_structure")
        self.actionName_nodes = QtGui.QAction(SnifferMainWindow)
        self.actionName_nodes.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/mail-tagged.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionName_nodes.setIcon(icon11)
        self.actionName_nodes.setObjectName("actionName_nodes")
        self.actionSelectPort = QtGui.QAction(SnifferMainWindow)
        self.actionSelectPort.setEnabled(True)
        self.actionSelectPort.setIcon(icon9)
        self.actionSelectPort.setObjectName("actionSelectPort")
        self.actionManual = QtGui.QAction(SnifferMainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/help-contents.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionManual.setIcon(icon12)
        self.actionManual.setObjectName("actionManual")
        self.actionAbout_sniffer = QtGui.QAction(SnifferMainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/help-about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_sniffer.setIcon(icon13)
        self.actionAbout_sniffer.setObjectName("actionAbout_sniffer")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSniffer.addAction(self.actionScan_channels)
        self.menuSniffer.addAction(self.actionScan_channel)
        self.menuSniffer.addAction(self.actionSniff)
        self.menuNetwork.addAction(self.actionStatistics)
        self.menuNetwork.addAction(self.actionName_nodes)
        self.menuSettings.addAction(self.actionSelectPort)
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionAbout_sniffer)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSniffer.menuAction())
        self.menubar.addAction(self.menuNetwork.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(SnifferMainWindow)
        QtCore.QMetaObject.connectSlotsByName(SnifferMainWindow)

    def retranslateUi(self, SnifferMainWindow):
        SnifferMainWindow.setWindowTitle(QtGui.QApplication.translate("SnifferMainWindow", "ZigBee Sniffer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("SnifferMainWindow", "Recived packets", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("SnifferMainWindow", "Packet info", None, QtGui.QApplication.UnicodeUTF8))
        self.treeDetails.setToolTip(QtGui.QApplication.translate("SnifferMainWindow", "Detailed packet info", None, QtGui.QApplication.UnicodeUTF8))
        self.treeDetails.headerItem().setText(1, QtGui.QApplication.translate("SnifferMainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.groupFile.setTitle(QtGui.QApplication.translate("SnifferMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNew.setToolTip(QtGui.QApplication.translate("SnifferMainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNew.setText(QtGui.QApplication.translate("SnifferMainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.btnImport.setToolTip(QtGui.QApplication.translate("SnifferMainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.btnImport.setText(QtGui.QApplication.translate("SnifferMainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setToolTip(QtGui.QApplication.translate("SnifferMainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("SnifferMainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.groupSniff.setTitle(QtGui.QApplication.translate("SnifferMainWindow", "Sniff", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSniff.setToolTip(QtGui.QApplication.translate("SnifferMainWindow", "Start/stop sniffing", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSniff.setText(QtGui.QApplication.translate("SnifferMainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.btnScanChannel.setToolTip(QtGui.QApplication.translate("SnifferMainWindow", "Start/stop channel scan", None, QtGui.QApplication.UnicodeUTF8))
        self.btnScanChannel.setText(QtGui.QApplication.translate("SnifferMainWindow", "Scan channel", None, QtGui.QApplication.UnicodeUTF8))
        self.btnScanChannels.setToolTip(QtGui.QApplication.translate("SnifferMainWindow", "Start/stop channels scan", None, QtGui.QApplication.UnicodeUTF8))
        self.btnScanChannels.setText(QtGui.QApplication.translate("SnifferMainWindow", "Scan channels", None, QtGui.QApplication.UnicodeUTF8))
        self.treeChannels.setToolTip(QtGui.QApplication.translate("SnifferMainWindow", "Select channel to operate in", None, QtGui.QApplication.UnicodeUTF8))
        self.groupNetwork.setTitle(QtGui.QApplication.translate("SnifferMainWindow", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNameNodes.setToolTip(QtGui.QApplication.translate("SnifferMainWindow", "Name nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStatistics.setToolTip(QtGui.QApplication.translate("SnifferMainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStatistics.setText(QtGui.QApplication.translate("SnifferMainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("SnifferMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSniffer.setTitle(QtGui.QApplication.translate("SnifferMainWindow", "Sniffer", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNetwork.setTitle(QtGui.QApplication.translate("SnifferMainWindow", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("SnifferMainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("SnifferMainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("SnifferMainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setToolTip(QtGui.QApplication.translate("SnifferMainWindow", "New file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("SnifferMainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setText(QtGui.QApplication.translate("SnifferMainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setToolTip(QtGui.QApplication.translate("SnifferMainWindow", "Import file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setShortcut(QtGui.QApplication.translate("SnifferMainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("SnifferMainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setToolTip(QtGui.QApplication.translate("SnifferMainWindow", "Save file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("SnifferMainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("SnifferMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScan_channels.setText(QtGui.QApplication.translate("SnifferMainWindow", "Scan channels", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScan_channels.setShortcut(QtGui.QApplication.translate("SnifferMainWindow", "F10", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScan_channel.setText(QtGui.QApplication.translate("SnifferMainWindow", "Scan channel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScan_channel.setShortcut(QtGui.QApplication.translate("SnifferMainWindow", "F9", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSniff.setText(QtGui.QApplication.translate("SnifferMainWindow", "Sniff", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSniff.setShortcut(QtGui.QApplication.translate("SnifferMainWindow", "F8", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPort_settings.setText(QtGui.QApplication.translate("SnifferMainWindow", "Port settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStatistics.setText(QtGui.QApplication.translate("SnifferMainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNetwork_structure.setText(QtGui.QApplication.translate("SnifferMainWindow", "Network structure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionName_nodes.setText(QtGui.QApplication.translate("SnifferMainWindow", "Name nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectPort.setText(QtGui.QApplication.translate("SnifferMainWindow", "Select port", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManual.setText(QtGui.QApplication.translate("SnifferMainWindow", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManual.setShortcut(QtGui.QApplication.translate("SnifferMainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_sniffer.setText(QtGui.QApplication.translate("SnifferMainWindow", "About sniffer", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
